site_name:           Rifraf.jl
repo_url:            https://github.com/MurrellGroup/Rifraf.jl
site_description:    A Julia package for the RIFRAF sequence consensus algorithm.
site_author:         Kemal Eren
theme:               material

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code

extra_css:
  - assets/Documenter.css

extra_javascript:
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Examples: examples.md
- API: api.md
